name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.0', 3.1, 3.2, 3.3, 3.4]
        gemfile: ['rails61', 'rails70', 'rails71', 'rails72', 'rails80']
        exclude:
          - ruby: 3.0
            gemfile: rails72
          - ruby: 3.0
            gemfile: rails80
          - ruby: 3.1
            gemfile: rails80

    name: ruby ${{ matrix.ruby }}, ${{ matrix.gemfile }}, ${{ matrix.database }}

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Bundle list
      run: |
        bundle list
    - name: Prepare test
      run: |
        cd spec/dummy
        BUNDLE_GEMFILE=../../${{ env.BUNDLE_GEMFILE }} RAILS_ENV=test bundle exec rake db:create db:migrate
        cd ../..
    - name: Run test
      run: |
        bundle exec rspec
